theme: jekyll-theme-minimal
title: Blockchain-Powered-Procurement-System
author: Team 8
email: eric7njuguna@gmail.com
keywords: "supply chain management, Procurement, Tenders, blockchain, Asili, unodc"
  
gems:
- jekyll-paginate
- jekyll-gist


